apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: elasticsearch
spec:
 replicas: 1
 selector:
   matchLabels:
     app.kubernetes.io/component: elasticsearch
 serviceName: elasticsearch
 template:
   metadata:
     labels:
       app.kubernetes.io/component: elasticsearch
   spec:
     terminationGracePeriodSeconds: 30
     securityContext:
       runAsUser: 1000
       runAsGroup: 1000
       fsGroup: 1000
     containers:
     - name: elasticsearch
       image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
       ports:
       - containerPort: 9600
       env:
         - name: discovery.type
           value: single-node
         - name: cluster.name
           value: elasticsearch
         - name: ES_JAVA_OPTS
           value: "-Xms512m -Xmx512m"
       resources:
         limits:
           memory: 2Gi
         requests:
           cpu: 100m
           memory: 1Gi
       volumeMounts:
       - name: elasticsearch-data
         mountPath: /usr/share/elasticsearch/data
 updateStrategy:
   type: RollingUpdate
 podManagementPolicy: OrderedReady
 volumeClaimTemplates:
 - metadata:
     name: elasticsearch-data
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 5Gi
